Switch ExperimentPage to use new filter field in SearchRuns
mlflow/mlflow pull request #1025
Opened 2019-03-22 00:55 UTC by andrewmchen

We added a new field in SearchRuns called filter which takes a string and parses the search filter on the server side. In this PR, we switch the UI component to use that field instead.

2019-03-22 23:57 UTC, dbczumar requested changes

2019-03-23 00:05 UTC, dbczumar commented
Throughout the testing process, I found that the following queries produce UI errors and / or don't work, despite the fact that they work on master (regressions):

1. `“params.A = ’74’”`: This produces a niagara falls screen (note that the whole query is wrapped in quotation marks) due to the following exception with the code `INTERNAL_ERROR` (500):

```
{"message": "Invalid clause(s) in filter string: '\"params.A = '74'\"'", "error_code": "INTERNAL_ERROR"}
```

2. `params.A > 74`: This also produces niagara falls due to the following `INTERNAL_ERROR`:
```
{"message": "Invalid comparator '>' not one of 'set(['=', '!='])", "error_code": "INTERNAL_ERROR"}
```

3. `params.A = "74"`: This query correctly selects runs that have the (parameter, value) pair (`A`, `74`) on `master` (where the UI is using anded expressions). With the UI + filters API updates, this produces ```Invalid filter string '"74"'. Filter comparison is expected as 'metric.<key> <comparator> <value>' or'params.<key> <comparator> <value>'.```

Observations:

1. As I discussed with @andrewmchen, search APIs probably shouldn't return `INTERNAL_ERROR` in  the case of the above failures; `INVALID_PARAMETER_VALUE` is more appropriate and is explicitly handled by the UI. (Relevant stakeholder: @mparkhe)

2. The UI should more gracefully handle the `INTERNAL_ERROR` case. Producing a Niagara falls image is particularly bad because we save the search query as a browser cookie. As a result, refreshing the page attempts to invoke the same query and produces yet another Niagara falls view. The only way to escape "perpetual Niagara falls" is to clear the browser cache.

2019-03-26 09:13 UTC, mparkhe commented
Some great catches @dbczumar. #1042 should address these.

2019-03-29 00:17 UTC, andrewmchen commented on mlflow/server/js/src/components/RunPage.js
> +          {(isLoading, shouldRenderError, requests) => {
QAed this bit manually.

2019-03-29 00:18 UTC, andrewmchen commented on mlflow/server/js/src/components/ExperimentPage.js
> +                return (<PermissionDeniedView
QAed this bit manually.

2019-03-29 17:32 UTC, andrewmchen commented on mlflow/server/js/src/Actions.js
> +        if (parsed.error_code && parsed.message) {
It means that the response came from our OSS server in the way we expect it to (it should always have an `error_code` field and a `message` field.

2019-03-29 17:33 UTC, andrewmchen commented on mlflow/server/js/src/components/RequestStateWrapper.js
> +    // (shouldRenderError: boolean, requests) => undefined | React Node.
Correct!

2019-04-02 00:04 UTC, mparkhe commented
@smurching and I tested with various different flavors. They all work with top of master

- `params."p name2" != ""`
- `params."p name2" = "a valid value"`
- `metrics.name > 0.23`
- `metrics."23_name_with_leading_number_quoted_key" > 0`

This is good to be merged in.

2019-04-02 19:58 UTC, merged