add release notes for registry changes
mlflow/mlflow pull request #10282
Opened 2023-11-02 15:01 UTC by BenWilson2

### Related Issues/PRs

 #xxx

### What changes are proposed in this pull request?

Add release card and contribution entry for the new Model Registry opt-in UI and pointers to alias support / cross-environment promotion support

### How is this PR tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [X] Manual tests

### Does this PR require documentation update?

- [ ] No. You can skip the rest of this section.
- [X] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

### Release Notes

#### Is this a user-facing change?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [X] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [X] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

2023-11-02 17:27 UTC, jerrylian-db requested changes
Thanks for putting this together! Left some suggested edits. Also, FYI: even though aliases feel like custom stages and were created to make stages more flexible, they are only part of the solution that replaces stages. Stages != aliases. Stages + stage transitions = tags + aliases + registered models + copy API.

2023-11-02 17:27 UTC, jerrylian-db commented on docs/source/new-features/index.rst
> +                        <a href="../model-registry.html#promoting-an-mlflow-model-across-environments">model promotion across environments</a> in the docs.
```suggestion
                        A new opt-in Model Registry UI has been built that uses Aliases and Tags for managing model development. See 
                       more about the new <a href="../model-registry.html#ui-workflow">UI workflow</a> in the docs.
```

2023-11-02 17:27 UTC, jerrylian-db commented on docs/source/new-features/index.rst
> +                        <a href="../model-registry.html#promoting-an-mlflow-model-across-environments">model promotion across environments</a> in the docs.
Here's a suggested edit. I'm removing the model promotion link because it does not yet affect the UI workflow. It will though in the next release.

2023-11-02 17:27 UTC, jerrylian-db commented on CHANGELOG.md
> +- [UI] Add support for alises and model tags for Model Registry custom stages (#10163, @jerrylian-db, @hubertzub-db)
```suggestion
- [UI] Add new opt-in Model Registry UI that supports model version aliases and tags (#10163, @hubertzub-db, @jerrylian-db)
```

2023-11-03 00:58 UTC, BenWilson2 commented
Thanks for the fixes @jerrylian-db :D

2023-11-06 17:15 UTC, jerrylian-db approved these changes

2023-11-06 17:16 UTC, merged