Asynchronous artifact logging
mlflow/mlflow pull request #11627
Opened 2024-04-05 03:21 UTC by jessechancy

### Related Issues/PRs

 #xxx

### What changes are proposed in this pull request?

Allows you to log artifacts asynchronously

### How is this PR tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

### Release Notes

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

2024-04-11 00:23 UTC, chenmoneygithub reviewed
This is actually my fault, I should have called this out earlier -  we can probably use python `asyncio` package to simplify the implementation. For metrics/params, the queue makes sense because we can do some grouping on our side (although we are not doing it now), but for artifact we should be able to use asyncio.

The syntax is like below, check this page: https://docs.python.org/3/library/asyncio-task.html
<img width="833" alt="image" src="https://github.com/mlflow/mlflow/assets/22925031/a79f1e27-c595-4fc9-a9ca-67b216a3dbf4">

2024-04-12 18:46 UTC, chenmoneygithub requested changes

2024-04-12 18:46 UTC, chenmoneygithub commented on mlflow/utils/async_logging/async_artifacts_logging_queue.py
> +        Args:
nit: put args section under class docstring instead of the `__init__`

2024-04-12 18:46 UTC, chenmoneygithub commented on mlflow/utils/async_logging/async_artifacts_logging_queue.py
> +                max_workers=10,
let's use a lower number: 5

2024-04-12 18:46 UTC, chenmoneygithub commented on mlflow/utils/async_logging/async_artifacts_logging_queue.py
> +                max_workers=10,
same

2024-04-12 18:46 UTC, chenmoneygithub commented on mlflow/utils/async_logging/async_artifacts_logging_queue.py
> +        self._batch_logging_thread = None
there is no `batch` here, let's call it `self._artifact_logging_thread`, and  the following as well.

2024-04-12 18:46 UTC, chenmoneygithub commented on mlflow/utils/async_logging/async_artifacts_logging_queue.py
> +        self._logging_func = artifact_logging_func
this could just be artifact logging function.

2024-04-12 18:46 UTC, chenmoneygithub commented on mlflow/tracking/_tracking_service/client.py
> +    def log_artifact_async(self, run_id, filename, artifact_path=None, callback=None):
make this private, so that only `log_artifact` is the public interface.

2024-04-12 18:46 UTC, chenmoneygithub commented on mlflow/store/artifact/artifact_repo.py
> +    def log_artifact_async(self, filename, artifact_path=None, callback=None):
same here

2024-04-12 18:46 UTC, chenmoneygithub commented on mlflow/tracking/client.py
> +            def callback(local_filepath):
nit: `save_compressed_image_callback()`

2024-04-12 18:46 UTC, chenmoneygithub commented on mlflow/tracking/client.py
> +            def callback(local_filepath):
nit: `save_image_callback()`

2024-04-12 18:46 UTC, chenmoneygithub commented on mlflow/utils/async_logging/async_artifacts_logging_queue.py
> +    def _log_run_data(self) -> None:
nit: `_log_artifact`

2024-04-13 00:01 UTC, chenmoneygithub requested changes
Thanks Jesse! I feel we do need to have testing to cover the async logging path, the current PR doesn't test the behavior, which is quite risky. It's fine to miss the Monday release, we can target the first patch release.

2024-04-17 22:31 UTC, chenmoneygithub approved these changes
Great work! LGTM with 2 small comments.

2024-04-17 22:31 UTC, chenmoneygithub commented on tests/utils/test_async_artifacts_logging_queue.py
> +    def __init__(self, throw_exception_on_artifact_number=None) -> None:
nit: let's don't use partial type annotation, we can just remove `-> None` here.

2024-04-17 22:31 UTC, chenmoneygithub commented on mlflow/utils/async_logging/run_artifacts.py
> +class RunArtifacts:
should this be singular form `RunArtifact`? in the constructor it's a single `artifact_path`

2024-04-19 17:50 UTC, merged

2024-04-22 08:40 UTC, harupy commented on mlflow/tracking/client.py
> +                and returns a future representing the logging operation.
Can we remove this? `log_artifact` doesn't have a `synchronous` argument.

2024-04-22 08:43 UTC, harupy commented on mlflow/store/artifact/artifact_repo.py
> +        self._async_logging_queue = AsyncArtifactsLoggingQueue(log_artifact_handler)
Should `mlflow.flush_async_logging` also flush async artifact logging?

2024-04-22 08:43 UTC, harupy commented on mlflow/__init__.py
>      flush_async_logging,
Should `mlflow.flush_async_logging` also flush async artifact logging?

2024-04-22 09:11 UTC, harupy commented on mlflow/__init__.py
>      flush_async_logging,
Do we need both `flush_artifact_async_logging` and `flush_async_logging`?

2024-04-22 10:12 UTC, harupy commented on mlflow/utils/async_logging/async_artifacts_logging_queue.py
> +            del state["_stop_data_logging_thread_event"]
We can use `.pop(key, None)` and a loop.

2024-04-22 10:13 UTC, harupy commented on mlflow/tracking/fluent.py
> +    run_id = _get_or_start_run().info.run_id
Should we really start a new run here?

2024-04-22 10:13 UTC, harupy commented on mlflow/tracking/fluent.py
> +    run_id = _get_or_start_run().info.run_id
We can use `mlflow.active_run` instead.

2024-04-22 10:20 UTC, harupy commented on mlflow/utils/async_logging/run_artifact.py
> +        """Initializes an instance of `RunArtifacts`.
`RunArtifact` -> `RunArtifact`

2024-04-22 10:20 UTC, harupy commented on mlflow/utils/async_logging/async_artifacts_logging_queue.py
> +        run_artifacts = None  # type: RunArtifact
should this be `run_artifact`?

2024-04-22 10:23 UTC, harupy commented on mlflow/utils/async_logging/async_artifacts_logging_queue.py
> +        run_artifacts = None  # type: RunArtifact
```
run_artifact: Optional[RunArtifact] = None
```

we can use an inline type hint instead.

2024-04-22 10:24 UTC, harupy commented on tests/utils/test_async_artifacts_logging_queue.py
> +    for num in range(1, len(filenames_sent)):
Curious why the range starts from 1.

2024-04-22 23:40 UTC, harupy commented on mlflow/utils/async_logging/async_artifacts_logging_queue.py
/ai review this code