Ensure unique constraint names in MLflow tracking database
mlflow/mlflow pull request #1292
Opened 2019-05-19 22:21 UTC by smurching

## What changes are proposed in this pull request?
 
The MLflow tracking database currently has multiple constraints with the same name. Several DBMSes (e.g. MySQL >= 8.0, MS SQL server) require unique constraint names, and so running an MLflow server with SQL-backed storage fails during table creation against these DBMSes. This PR updates the MLflow tracking database schema to contain unique constraint names, adding a database migration to accomplish this for existing users of SQL-backed storage.
 
## How is this patch tested?
 
(Details)
 
## Release Notes
 
### Is this a user-facing change? 

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
Fixes an issue where the MLflow tracking database had multiple constraints with the same name, thereby enabling running an MLflow tracking server against a DBMS that requires unique constraint names (e.g. MySQL >= 8.0).
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [x] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

2019-05-21 23:23 UTC, dbczumar requested changes
@smurching Left a couple nits and small documentation comments. As we discussed offline, there appears to be a migration ordering issue that we need to address prior to merging.

2019-05-21 23:23 UTC, dbczumar commented on mlflow/store/sqlalchemy_store.py
> +                    "Detected out-of-date database schema (found version %s, but expected %s)."
Nit: Missing space between the period and `Take` in the next sentence:

```
mlflow.exceptions.MlflowException: Detected out-of-date database schema (found version 451aebb31d03, but expected ff01da956556).Take a backup of your database, then run 'mlflow db upgrade sqlite:///mydb' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
```

2019-05-22 18:22 UTC, smurching commented on mlflow/temporary_db_migrations_for_pre_1_users/alembic.ini
> +# A generic, single database configuration.
This whole directory is a copy of the existing `alembic` directory, except containing a different set of migrations (the migration for pre-1.0 users) under the `versions` subdirectory

2019-05-22 18:23 UTC, smurching commented on mlflow/temporary_db_migrations_for_pre_1_users/versions/ff01da956556_ensure_unique_constraint_names.py
> +"""ensure_unique_constraint_names
This is the one-time migration for pre-1.0 users to rename constraints with duplicate names

2019-05-22 22:53 UTC, dbczumar approved these changes
LGTM! Thanks @smurching. I tested the upgrade flow from `v0.9.1` and ensured that adding subsequent migrations does not break the `mlflow db upgrade` or fresh DB initialization flow.

2019-05-22 23:48 UTC, merged