[ALL TESTS] Update
mlflow/mlflow pull request #2011
Opened 2019-10-28 23:22 UTC by sueann

2019-10-28-23-21-55-083183 Update

2019-10-28 23:58 UTC, stbof commented on CHANGELOG.rst
> +- Get ``models serve`` CLI command to work in Windows (#1949, @rboyes)
Get ``models serve`` CLI command to work in Windows  -> ``models serve`` CLI command now works in Windows

2019-10-28 23:58 UTC, stbof commented on CHANGELOG.rst
> +Small bug fixes and doc updates (#1914, @jerrygb; #1978, #1894, @smurching; #1940, #1900, #1904, @mparkhe; #1966, #1955, #1952, @Djailla; #1932, #1935, @harupy)
Fix dependency-installation bug -> Fix dependency installation bug

2019-10-28 23:59 UTC, stbof commented on CHANGELOG.rst
> +
Suggest a category - TensorFlow 2.0 updates and put these two under it.

2019-10-29 00:00 UTC, stbof commented on CHANGELOG.rst
> +- Use Plotly as artifact image viewer to make it interactive (#1934, @harupy)
Use Plotly as artifact image viewer to make it interactive 

What does "it" appy to?

2019-10-29 00:01 UTC, ghost requested changes
See inline comments

2019-10-29 00:53 UTC, mateiz commented on CHANGELOG.rst
> +- Model Registry. MLflow 1.4 adds an experimental model registry feature, where you can manage, version, and keep lineage of your production models. (#1943, @mparkhe, @Zangr, @sueann, @dbczumar, @smu
It might be better to call the registry beta so people know that it's still early on.

2019-10-30 17:09 UTC, ghost approved these changes

2019-10-30 18:51 UTC, merged