add health endpoint
mlflow/mlflow pull request #2610
Opened 2020-03-20 10:27 UTC by kasparg

## What changes are proposed in this pull request?

Add health endpoint

## How is this patch tested?

(Details)

## Release Notes

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s) does this PR affect?

- [ ] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

2020-03-20 10:28 UTC, ivan-transferwise approved these changes

2020-03-20 20:45 UTC, tomasatdatabricks commented
Hey @kasparg , thanks for the contribution. Can you also add a test for the new endpoint and update documentation?

2020-03-20 22:46 UTC, andychow-db commented
I've updated the description to indicate it is a new API. It'll require some documentation and information.

Secondly, if you're looking for health, I suggest using `/ping` rather than `/health`.

2020-03-20 22:48 UTC, andychow-db commented on mlflow/server/__init__.py
> +# Add health endpoint
Nit: `Add health endpoint` is not the correct comment here. Please update it.

2020-03-25 09:43 UTC, gopalsi approved these changes

2020-04-02 04:39 UTC, mparkhe commented
hi @kasparg : as recommended by @tomasatdatabricks, can you please add a test for the new endpoint?

2020-04-15 19:22 UTC, aarondav requested changes
A minor test and update to the doc comment are requested!

2020-04-17 15:46 UTC, aarondav commented
Looks like @crflynn addressed these comments in #2725, which was merged. Thanks!

2020-04-17 15:46 UTC, closed without merging