MLeap Flavor/Deployment #1: Support for multiple Spark model flavors
mlflow/mlflow pull request #311
Opened 2018-08-16 19:49 UTC by dbczumar

This is the **second** PR in a multi-part series that will introduce support for the MLeap flavor in MLFlow. 

This PR moves serialization logic specific to Spark MLLib (SparkML) into a separate `sparkml.py` module. In a following PR, we will add an `mleap.py` module. The existing `spark.py` module will still be used as the entrypoint for serializing PySpark models; it will leverage `sparkml.py` and `mleap.py` to output supported flavors at serialization time.

2018-08-16 19:50 UTC, dbczumar commented on mlflow/sparkml.py
> +"""
@tomasatdatabricks Is `mllib.py` a better name for this module? @aarondav Pointed out that the current name is very similar to `spark.py`

2018-08-17 18:01 UTC, tomasatdatabricks requested changes
Looks good, thanks Corey!

I left a few comments, most of them minor. My only concerns is that I don't like how we handle the model save. I think we should catch exceptions, we can let users specify which flavors they want and fail the method if any of the requested flavors fails to save.

2018-08-17 18:03 UTC, tomasatdatabricks commented on mlflow/sparkml.py
> +    sparkml_datapath_sub = os.path.join("sparkml", "model")
Oh and I would prefer if sparkml.add_to_model would be called save_model, cause that's more consistent with how other things are named.

2018-08-17 21:42 UTC, dbczumar commented
After discussing the structure of this PR with @tomasatdatabricks, we agree that preserving `spark.py` as the MLLib-specific point of entry makes more sense. `spark.py` will still contain logic for MLLib pipeline serialization and call out to a separate `mleap.py` method to add the MLeap flavor, if relevant.

This is superseded by #324

2018-08-17 21:42 UTC, closed without merging