[WIP] Use allowlisted APIs to fetch information on clusters
mlflow/mlflow pull request #3398
Opened 2020-09-07 23:03 UTC by smurching

## What changes are proposed in this pull request?

Use new, allowlisted APIs to fetch information on clusters when DataFrame ACLs are enabled. We fall back to using existing APIs for backwards compatibility with older runtime versions.

## How is this patch tested?

TODO

## Release Notes

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

2020-09-08 14:14 UTC, nfx requested changes

2020-09-08 14:14 UTC, nfx commented on mlflow/utils/databricks_utils.py
> +        print("Yo fro msid")
please remove this debug line

2020-09-08 18:29 UTC, smurching commented on mlflow/utils/databricks_utils.py
> +        print("Yo fro msid")
Oops, haha thanks for the catch!

2020-09-09 17:34 UTC, nfx requested changes
remove lint ignores and catch exact exceptions

2020-09-09 17:34 UTC, nfx commented on mlflow/utils/databricks_utils.py
> +    except Exception:  # pylint: disable=broad-except
can you catch exact exception here and remove pylint disable?

2020-09-09 17:34 UTC, nfx commented on mlflow/utils/databricks_utils.py
> +    except Exception:  # pylint: disable=broad-except
remove `# pylint: disable=broad-except` and catch exact exception

2020-09-09 17:34 UTC, nfx commented on mlflow/utils/databricks_utils.py
> +    except Exception:  # pylint: disable=broad-except
remove # pylint: disable=broad-except and catch exact exception

2020-09-10 07:04 UTC, smurching commented
@nfx it's a good question whether we can catch a more specific exception type. It turns out Py4j (at least the current release of Py4j) will only ever raise instances of Py4jError ([docs](https://www.py4j.org/advanced_topics.html#py4j-exceptions)). However, since our goal is to support older runtime versions with the current MLflow client (which may have older versions of Py4j or other hard-to-test behavior), it seems the least risky option is to try the new behavior of using allowlisted APIs, and fall back to the existing behavior in case of any exceptions, rather than try to catch a specific exception and find that we've broken behavior on existing runtimes.

One other subtlety worth noting in case we revisit this in the future - `py4j` is intentionally not a dependency of MLflow. In order to catch `Py4jError`, we may be tempted to `from py4j.protocol import Py4jError` at the top level of the `databricks_utils` module, i.e. make it dependent on `py4j`. However since `databricks_utils` is occasionally used in contexts outside of Databricks (e.g. when triggering execution of MLflow projects remotely on Databricks from your laptop), we should instead perform all `py4j` imports inside functions where they're used & ensure these functions are only called on Databricks.

2020-09-11 13:24 UTC, nfx commented
@smurching the pain point of catching `Exception` is that it can catch OSError, KeyError, ZeroDivisionError and other dangerous things. if we explicitly don't want to add py4j dependency, then i'd agree with your comment.

2020-09-13 21:56 UTC, tomasatdatabricks approved these changes
lgtm

2020-09-17 18:40 UTC, merged