Update type of input json data to `StringIO`
mlflow/mlflow pull request #3921
Opened 2020-12-29 09:07 UTC by Secbone

## What changes are proposed in this pull request?

Fix error when scoring_serving parsing input JSON with pandas version later than `1.1.0`. 

Fixed #3920 

## How is this patch tested?

(Details)

## Release Notes

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

2021-01-27 00:52 UTC, pogil commented
@tomasatdatabricks, would you please take a look?

2021-01-27 01:37 UTC, tomasatdatabricks requested changes
Thanks for the PR @Secbone.
 2 comments/ requests:

  1. The PR is out of sync with master (sorry for the delayed review!). Can you please update it?
  2. Can you add a test?

2021-01-28 05:35 UTC, Secbone reviewed
I have merged the master branch and added a test case for it

2021-01-28 17:37 UTC, tomasatdatabricks approved these changes
lgtm. Thanks @Secbone!

2021-01-28 18:19 UTC, tomasatdatabricks commented
Hi @Secbone, thanks for the udpates! 

I've approved the PR but it looks like the tests are stuck and I am having trouble restarting them on github. Would you mind pushing an extra empty commit to run the tests again? Something like this `git commit --allow-empty -m "Trigger Build"`.

2021-02-01 10:28 UTC, Secbone commented
@tomasatdatabricks I have fixed the test problem, would you please take a look?

2021-02-01 18:49 UTC, merged