Add example for Ray Serve deployment plugin
mlflow/mlflow pull request #4029
Opened 2021-01-28 01:06 UTC by architkulkarni

## What changes are proposed in this pull request?

This PR adds a basic example of using the MLflow Ray Serve deployment plugin.  In the example, a model is trained to classify the Iris dataset using `sklearn`. Next, the model is deployed on Ray Serve and scaled up.

This PR also adds the Ray Serve plugin to the list of known third-party deployment plugins in the MLflow documentation.

## How is this patch tested?

A test has been added alongside the rest of the example tests.
## Release Notes

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)
Add usage example for MLflow Ray Serve deployment plugin
### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [x] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

2021-01-28 17:32 UTC, dmatrix commented
@architkulkarni You will want to [sign your commits](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst#sign-your-work), for the DCO test to succeed.

2021-01-28 19:45 UTC, architkulkarni commented
Thanks @dmatrix, apologies for the oversight.  It's fixed now.

2021-01-28 23:51 UTC, dmatrix requested changes
Shouldn't that be

2021-01-28 23:53 UTC, dmatrix requested changes
Shouldn't this be the `-m model-uri?`

2021-02-05 00:21 UTC, architkulkarni commented on examples/ray_serve/README.md
> +First, run `train_model.py`.  This trains and saves our classifier and sets up automatic logging to MLflow.  It also prints the mean squared error and the target names, which are species of iris:
Thanks, that makes sense!  It should be more readable now.

2021-02-05 00:55 UTC, dmatrix reviewed
LGTM with the sequence of steps.

2021-02-05 01:08 UTC, harupy commented on examples/ray_serve/train_model.py
> +np.random.shuffle(target)
Should we avoid shuffling `data` and `target` separately?

2021-02-05 01:31 UTC, harupy commented on examples/ray_serve/train_model.py
> +np.random.shuffle(target)
I think we can use https://scikit-learn.org/stable/modules/generated/sklearn.utils.shuffle.html

2021-02-19 19:11 UTC, dmatrix commented on examples/ray_serve/README.md
> +First, navigate to the directory for this example, `/mlflow/examples/ray_serve/`.
should that be relative path `mlflow/examples/ray_serv/`

2021-02-19 19:13 UTC, dmatrix commented on examples/ray_serve/README.md
> +Next, start a long-running Ray Serve instance on our Ray cluster:
Should that pronoun me `your`? Our suggests it's maintained outside, elsewhere.

2021-02-19 19:15 UTC, dmatrix commented on examples/ray_serve/README.md
> +Finally, we may deploy our model by creating an instance using the following command:
Perhaps `can` is better than using tentative `may`

2021-02-19 19:17 UTC, dmatrix commented on examples/ray_serve/README.md
> +The `-t` parameter here is the deployment target, which in our case is Ray Serve.  The `-m` parameter is the Model URI, which consists of the model name and model version.
maybe say:  which consists of the registered model name and version in the Model Registry.

2021-02-19 19:23 UTC, dmatrix commented on examples/ray_serve/train_model.py
> +def print_model_info(m_uri, x):
I know I wrote this code bit. Perhaps call this function `eval_and_print_model_info(...)`

2021-02-19 19:24 UTC, dmatrix reviewed
Added minor nits and suggestions.

2021-02-19 20:37 UTC, architkulkarni commented
Thanks a lot for the detailed review!  I implemented the suggestions and got rid of `print_model_info` since it isn't used in the example and I forgot to remove it earlier.

2021-02-19 21:54 UTC, dmatrix approved these changes
LGTM :)

2021-03-02 23:58 UTC, harupy approved these changes
LGTM :)

2021-03-02 23:59 UTC, harupy commented
@architkulkarni The flavors check should be fixed by merging the master branch.

2021-03-03 00:53 UTC, architkulkarni commented
@harupy Thanks, it worked!

2021-03-03 01:24 UTC, merged