[WIP] Add support for SpaCy text classification models
mlflow/mlflow pull request #610
Opened 2018-10-08 13:06 UTC by suzil

Refs: https://github.com/mlflow/mlflow/issues/500

2018-10-08 21:06 UTC, mparkhe requested changes
Hi @suzil : Thanks for this pull request. There are some lint errors. Also made a couple of change requests, one of them should help resolve most of the lint issues.

2018-10-08 21:06 UTC, mparkhe commented on examples/spacy/text_classification.py
> +@plac.annotations(
Can we use `click` for this?

Here are a couple of references:
1. [cli.py](https://github.com/mlflow/mlflow/blob/master/mlflow/cli.py)
2. [hyperparam/train.py](https://github.com/mlflow/mlflow/blob/master/examples/hyperparam/train.py#L111)

2018-10-10 17:29 UTC, mparkhe reviewed
Hi @suzil : couple of small comments. I tried out the code -- it looks cool. Thanks for adding this flavor and example.

2018-10-10 17:29 UTC, mparkhe commented on examples/spacy/text_classification.py
> +            mlflow.spacy.log_model(nlp, "model")
Please extend this example to load this saved model and predict.
alternatively, add a unit test to cover the log_model and load_model flow.

2018-10-17 14:13 UTC, suzil commented
Hi @mparkhe. Thanks so much for the feedback.

I have a question: how should I handle passing a ["mode" parameter](https://github.com/mlflow/mlflow/pull/610/files#diff-fcf5da7aba04355ed78ee4c3c04a9b40R128) to specify the kind of model SpaCy should make predictions on? I handle it in the code by having the user pass an extra blank row that includes a column called "mode", but this feels very kludgey.

2018-10-17 16:49 UTC, tomasatdatabricks commented
Hi @suzil. That is a very good question. 

I would recommend storing the desired mode with the model - i.e. you add the argument to mlflow.spacy.save_model and store it with the model data. The produced pyfunc would then only score the one specified mode. This has a disadvantage that you need to produce multiple copies o the same model if you need to score different modes as pyfunc but it is imho better than encoding mode with the data and I don't see other good way around it.

2019-07-29 07:35 UTC, suzil commented
Closing due to staleness.

2019-07-29 07:35 UTC, closed without merging

2019-12-05 23:44 UTC, TheTravellingSalesman commented
Is the branch for this PR still available somewhere? I'm interested in picking up this development.