Fix databricks config fetch in R client for DBR 13.x versions
mlflow/mlflow pull request #8135
Opened 2023-03-30 18:27 UTC by apurva-koti

## What changes are proposed in this pull request?

User context variables are no longer passed directly into the env in 13.x versions. Use the spark property fetch to get variables instead.

## How is this patch tested?
Manually on a 13.x version.

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

## Release Notes

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [x] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [x] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

2023-03-30 18:28 UTC, apurva-koti commented on mlflow/R/mlflow/R/databricks-utils.R
> +  } else if (require("SparkR") &&
`require("SparkR")` returns true if SparkR is installed. Obviously we expect this code to be run on databricks so `library('SparkR')` shouldn't be necessary.

2023-03-30 18:45 UTC, mlflow-automation commented
<!-- documentation preview -->


Documentation preview for 514d0d887d67560e3acb61298522b9064074f5fa will be available [here](https://output.circle-artifacts.com/output/job/cf864de2-075f-4181-8e49-4bb0e4e34bcf/artifacts/0/docs/build/html/index.html) when [this CircleCI job](https://circleci.com/gh/mlflow/mlflow/44679) completes successfully.

<details>
<summary>More info</summary>

- Ignore this comment if this PR does not change the documentation.
- It takes a few minutes for the preview to be available.
- The preview is updated when a new commit is pushed to this PR.
- This comment was created by https://github.com/mlflow/mlflow/actions/runs/4567762642.

</details>

2023-03-30 23:13 UTC, harupy approved these changes
LGTM!

2023-03-31 00:11 UTC, WeichenXu123 approved these changes
LGTM, thanks!

2023-03-31 00:47 UTC, dbczumar requested changes
Blocking temporarily because Spark local properties aren't available on workers. Apologies for the confusion

2023-03-31 01:07 UTC, WeichenXu123 commented
Can we set spark config spark.executorEnv.[EnvironmentVariableName] as a workround ?
e.g. if we set spark.executorEnv.ABC  to be value XYZ,
then in spark UDF we can read environment variable "ABC" with value "XYZ"

2023-04-05 23:09 UTC, apurva-koti commented
Client changes not needed.

2023-04-05 23:09 UTC, closed without merging