[WIP] Server-side implementation of batched logging endpoints
mlflow/mlflow pull request #951
Opened 2019-03-04 22:51 UTC by smurching

This PR is a follow-up to #950 adding support for logging batches to a remote server, as well as server-side handlers for batched logging, and associated unit tests.

The diff from #950 is:
```
 mlflow/server/handlers.py      | 42 ++++++++++++++++++++++++++++++++++++++++--
 mlflow/store/rest_store.py     | 25 ++++++++++++++++++++++++-
 tests/server/test_handlers.py  |  3 +++
 tests/store/test_rest_store.py | 15 ++++++++++++++-
```

2019-03-07 22:24 UTC, mparkhe requested changes
copy paste error in `_log_batch` handler.

2019-03-07 22:24 UTC, mparkhe commented on mlflow/server/handlers.py
> +    request_message = _get_request_message(ListExperiments())
This should be -

```
    request_message = _get_request_message(LogBatch())
```

2019-03-11 05:39 UTC, mparkhe commented on tests/store/test_rest_store.py
> +        with mock.patch('mlflow.store.rest_store.http_request_safe') as mock_http:
let's add example(s) with real batches.
- a bunch of just metrics, tags and params are empty
- just tags,
- one tag, and a bunch of params
- params and tags with the same key
- metric and param batches swapped in API call, and other such error cases
- ... etc

ideally, we should have a generic test that is super comprehensive with all these options and applied to a any backend and ensure that the behavior is as intended

2019-03-12 00:46 UTC, smurching commented
@mparkhe as per offline discussion, I ended up adding a couple of simple test cases to more thoroughly verify the end-to-end server functionality (i.e. actually integration-test against a real AbstractStore implementation instead of just verifying that the right AbstractStore methods are called).

Also created https://github.com/mlflow/mlflow/issues/984 to track adding a new test harness for verifying AbstractStore implementations (I think a good way to do this could be to just refactor the existing FileStore & SqlAlchemyStore unit tests into a single test module parametrized by store type)

2019-03-12 00:58 UTC, mparkhe approved these changes
LGTM

2019-03-12 00:58 UTC, mparkhe commented on tests/server/test_handlers.py
> +def test_log_batch_handler_success(mock_get_request_message, tmpdir):
this is really an awesome test -- at some point we can use the `@pytest.mark.parametrize` to send it different stores.

2019-03-12 05:02 UTC, merged