[LLM-eval] Adding context variables, input and multi output option
mlflow/mlflow pull request #9661
Opened 2023-09-18 22:09 UTC by sunishsheth2009

## What changes are proposed in this pull request?
[LLM-eval] Adding context variables, input and multi output option

## How is this patch tested?
- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests (describe details, including test results, below)

## Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

## Release Notes

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

2023-09-18 22:09 UTC, mlflow-automation commented
<!-- documentation preview -->


Documentation preview for 1cee4f4973383aa79c1b564e466491353397c138 will be available [here](https://output.circle-artifacts.com/output/job/f0503ab5-c7b8-455c-85a9-692169abc1e8/artifacts/0/docs/build/html/index.html) when [this CircleCI job](https://circleci.com/gh/mlflow/mlflow/65455) completes successfully.

<details>
<summary>More info</summary>

- Ignore this comment if this PR does not change the documentation.
- It takes a few minutes for the preview to be available.
- The preview is updated when a new commit is pushed to this PR.
- This comment was created by https://github.com/mlflow/mlflow/actions/runs/6228540487.

</details>

2023-09-19 05:05 UTC, prithvikannan requested changes

2023-09-19 05:05 UTC, prithvikannan commented on mlflow/models/evaluation/default_evaluator.py
>              # in case the user modifies them inside their function(s).
can we please update this comment to explain this logic better

2023-09-19 05:05 UTC, prithvikannan commented on mlflow/models/evaluation/default_evaluator.py
> +def _extract_output_and_other_columns(model_predictions, output_column_name):
in this function `model_predictions` comes from `self.model.predict`, which can return pandas.DataFrame, pandas.Series, numpy.ndarray or list ([docs](https://mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#mlflow.pyfunc.PyFuncModel.predict)). can we make sure to handle all of these cases?

2023-09-20 18:46 UTC, prithvikannan commented on mlflow/models/evaluation/base.py
> +                    corresponding variables values used for making the evaluations.
```suggestion
                    A Pandas or Spark DataFrame containing ``prediction``, ``target``,
                    various ``variables``, optional ``input`` column.
                    For each row...
                    - the ``prediction`` contains the prediction made by the model.
                    - the ``target`` contains the the expected output/label.
                    - the ``variables`` contain other outputs from the model that are used for making the evaluations.
                    - the optional ``input`` contains the input sent into the model.
```

2023-09-20 21:20 UTC, sunishsheth2009 commented on mlflow/models/evaluation/base.py
> +                    were made.
Spoke offline. We only consider the input for the LLM usecase which maps to the input column.

2023-09-20 22:26 UTC, prithvikannan approved these changes
LGTM, thanks @sunishsheth2009

2023-09-21 16:21 UTC, merged